apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: jagdeep144/frontend-shopping:v4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000 
        env: 
          - name:  REACT_APP_API_URL
            value: "http://gateway-service:3001/api"
          
        resources:
          requests: 
            cpu: "200m"
            memory: "300Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopping 
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP 

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: shopping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment 
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10  



   